### ISSUE TITLE
to-do list: `MultipliableMatrix`s

### ISSUE THREAD

**Issue by ggebbie** [ggebbie/MultipliableMatrices.jl#1]
- [x] constructor for Squarable matrices
- [x] identity matrix
- [x] struct for DimensionallySymmetric matrices
- [x] define matrix-matrix multiply
- [x] check result of inverse in runtest_Hart
- [x] `set_index!`: possible with these struct types?
- [x] SVD for non-uniform matrices
- [x] Directly use LU object for matrix operations
- [x] philosophy added to README (performant, within Linear Algebra constructs, naming)
- [x] Highlights (i.e., Main Usage) added to README
- [x] Benchmarks
            - matrix multiplication is slow
- [x] use SVD object
- [x] create DSVD object
- [ ] `blkdiag`          
- [ ] add `convert` for AbstractMultipliableMatrix to Matrix
- [x] Directly use Cholesky object for matrix operations
- [ ] equality for AbstractMultipliableMatrix
- [ ] AbstractMultipliableMatrix interface added to README
- [ ] inv (other functions) for DSVD
- [x] `eigen` for squarable matrices
- [ ] Are any issues from other repos (i.e., Unitful.jl) solved?
          - [x] sparse and backslash operators work
          - [ ] StridedArrays issue not addressed
          - [ ] views of Sparse Arrays not addressed

**Comment by ggebbie** [comment]
~~identity matrix~~

**Comment by ggebbie** [comment]
~~define matrix-matrix multiply
check result of inverse in runtest_Hart~~

**Comment by ggebbie** [comment]
~~slices of multipliable matrices~~
